/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface WoActionSheet {
    /**
    * 激活颜色
    */
    'activeColor': string;
    /**
    * 列表数据
    */
    'lists': Array<any>;
    'setAction': (index: any) => void;
    /**
    * 显示
    */
    'show': boolean;
    /**
    * 标题
    */
    'title': string;
  }
  interface WoActionSheetAttributes extends StencilHTMLAttributes {
    /**
    * 激活颜色
    */
    'activeColor'?: string;
    /**
    * 列表数据
    */
    'lists'?: Array<any>;
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 显示
    */
    'show'?: boolean;
    /**
    * 标题
    */
    'title'?: string;
  }

  interface WoButton {
    /**
    * 是否禁用 默认值   false 可选值   true
    */
    'disabled': boolean;
    /**
    * 幽灵按钮 默认值  false 可选值   true
    */
    'plain': boolean;
    /**
    * 按钮形状 默认值   - 可选值   square  round
    */
    'shape': string;
    /**
    * 按钮尺寸 默认值   normal 可选值   small  large
    */
    'size': string;
    /**
    * 按钮类型 默认值 default 可选值 primary info danger warning
    */
    'type': string;
  }
  interface WoButtonAttributes extends StencilHTMLAttributes {
    /**
    * 是否禁用 默认值   false 可选值   true
    */
    'disabled'?: boolean;
    /**
    * 对外提供 touchStart事件响应
    */
    'onClicked'?: (event: CustomEvent) => void;
    /**
    * 对外提供 touchStart事件响应
    */
    'onTouched'?: (event: CustomEvent) => void;
    /**
    * 幽灵按钮 默认值  false 可选值   true
    */
    'plain'?: boolean;
    /**
    * 按钮形状 默认值   - 可选值   square  round
    */
    'shape'?: string;
    /**
    * 按钮尺寸 默认值   normal 可选值   small  large
    */
    'size'?: string;
    /**
    * 按钮类型 默认值 default 可选值 primary info danger warning
    */
    'type'?: string;
  }

  interface WoCellGroup {
    /**
    * 是否显示底线
    */
    'bottomLine': boolean;
    /**
    * 是否显示顶线
    */
    'topLine': boolean;
  }
  interface WoCellGroupAttributes extends StencilHTMLAttributes {
    /**
    * 是否显示底线
    */
    'bottomLine'?: boolean;
    /**
    * 是否显示顶线
    */
    'topLine'?: boolean;
  }

  interface WoCell {
    'bottomLine': boolean;
    'isScroll': boolean;
    'label': string;
    /**
    * 说明文字颜色
    */
    'labelColor': string;
    /**
    * 说明文字大小
    */
    'labelSize': string;
    /**
    * 单元格 上/下 线
    */
    'topLine': boolean;
  }
  interface WoCellAttributes extends StencilHTMLAttributes {
    'bottomLine'?: boolean;
    'isScroll'?: boolean;
    'label'?: string;
    /**
    * 说明文字颜色
    */
    'labelColor'?: string;
    /**
    * 说明文字大小
    */
    'labelSize'?: string;
    /**
    * 单元格 上/下 线
    */
    'topLine'?: boolean;
  }

  interface WoColorChoose {
    'activeColor': string | null;
    'lists': Array<any>;
    'setColor': (item: any) => void;
    'size': string;
  }
  interface WoColorChooseAttributes extends StencilHTMLAttributes {
    'activeColor'?: string | null;
    'lists'?: Array<any>;
    'onChange'?: (event: CustomEvent) => void;
    'size'?: string;
  }

  interface WoCount {
    /**
    * 改变底线颜色
    */
    'changeColor': () => void;
    /**
    * 输入
    */
    'changeValue': () => void;
    /**
    * 输入框内文字颜色
    */
    'color': string;
    /**
    * 减小
    */
    'decreaseValue': () => void;
    /**
    * 增大
    */
    'increaseValue': () => void;
    /**
    * 底线颜色
    */
    'lineColor': string;
    /**
    * 最大值
    */
    'max': number;
    /**
    * 最小值
    */
    'min': number;
    /**
    * 步长
    */
    'step': number;
    /**
    * 默认值
    */
    'value': number;
  }
  interface WoCountAttributes extends StencilHTMLAttributes {
    /**
    * 输入框内文字颜色
    */
    'color'?: string;
    /**
    * 底线颜色
    */
    'lineColor'?: string;
    /**
    * 最大值
    */
    'max'?: number;
    /**
    * 最小值
    */
    'min'?: number;
    /**
    * 对外提供当前模式数据
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 步长
    */
    'step'?: number;
    /**
    * 默认值
    */
    'value'?: number;
  }

  interface WoMain {
    /**
    * 更改设备开关状态
    */
    'changeState': () => void;
    /**
    * 设备图片路径
    */
    'imageUrl': string;
    /**
    * 设备开关状态
    */
    'isOpen': boolean;
    /**
    * 设备所属房间
    */
    'location': string;
  }
  interface WoMainAttributes extends StencilHTMLAttributes {
    /**
    * 设备图片路径
    */
    'imageUrl'?: string;
    /**
    * 设备开关状态
    */
    'isOpen'?: boolean;
    /**
    * 设备所属房间
    */
    'location'?: string;
    /**
    * 获取设备开关状态
    */
    'onChange'?: (event: CustomEvent) => void;
  }

  interface WoMode {
    /**
    * 选中时的背景颜色
    */
    'activeBackground': string;
    /**
    * 选中时的文字颜色
    */
    'activeColor': string;
    /**
    * 未选中时的背景颜色
    */
    'background': string;
    /**
    * 未选中时的文字颜色
    */
    'color': string;
    /**
    * 模式数组
    */
    'lists': Array<Mode>;
    /**
    * 设置当前的模式
    */
    'setMode': (item: any) => void;
  }
  interface WoModeAttributes extends StencilHTMLAttributes {
    /**
    * 选中时的背景颜色
    */
    'activeBackground'?: string;
    /**
    * 选中时的文字颜色
    */
    'activeColor'?: string;
    /**
    * 未选中时的背景颜色
    */
    'background'?: string;
    /**
    * 未选中时的文字颜色
    */
    'color'?: string;
    /**
    * 模式数组
    */
    'lists'?: Array<Mode>;
    /**
    * 对外提供当前模式数据
    */
    'onChange'?: (event: CustomEvent) => void;
  }

  interface WoProgress {
    /**
    * 进度条激活状态颜色
    */
    'activeColor': string;
    'calculateValue': (left: any) => void;
    /**
    * 圆颜色
    */
    'circleColor': string;
    'clickMode': (e: any) => void;
    /**
    * 字颜色
    */
    'color': string;
    'getCirclePos': (e: any) => void;
    /**
    * 是否置灰
    */
    'inactive': boolean;
    /**
    * 进度条默认状态颜色
    */
    'inactiveColor': string;
    /**
    * 最大值
    */
    'max': number;
    /**
    * 最小值
    */
    'min': number;
    /**
    * 是否显示百分比
    */
    'percent': boolean;
    'touchEventEnd': () => void;
    /**
    * 传入的值
    */
    'value': number;
  }
  interface WoProgressAttributes extends StencilHTMLAttributes {
    /**
    * 进度条激活状态颜色
    */
    'activeColor'?: string;
    /**
    * 圆颜色
    */
    'circleColor'?: string;
    /**
    * 字颜色
    */
    'color'?: string;
    /**
    * 是否置灰
    */
    'inactive'?: boolean;
    /**
    * 进度条默认状态颜色
    */
    'inactiveColor'?: string;
    /**
    * 最大值
    */
    'max'?: number;
    /**
    * 最小值
    */
    'min'?: number;
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 是否显示百分比
    */
    'percent'?: boolean;
    /**
    * 传入的值
    */
    'value'?: number;
  }

  interface WoSwitch {
    'activeColor': string;
    'checked': boolean;
    /**
    * 是否禁用
    */
    'disabled': boolean;
    /**
    * 关闭时的背景色
    */
    'inactiveColor': string;
    /**
    * 开关大小
    */
    'size': string;
  }
  interface WoSwitchAttributes extends StencilHTMLAttributes {
    'activeColor'?: string;
    'checked'?: boolean;
    /**
    * 是否禁用
    */
    'disabled'?: boolean;
    /**
    * 关闭时的背景色
    */
    'inactiveColor'?: string;
    /**
    * 对外提供当前模式数据
    */
    'onChange'?: (event: CustomEvent) => void;
    /**
    * 开关大小
    */
    'size'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WoActionSheet': Components.WoActionSheet;
    'WoButton': Components.WoButton;
    'WoCellGroup': Components.WoCellGroup;
    'WoCell': Components.WoCell;
    'WoColorChoose': Components.WoColorChoose;
    'WoCount': Components.WoCount;
    'WoMain': Components.WoMain;
    'WoMode': Components.WoMode;
    'WoProgress': Components.WoProgress;
    'WoSwitch': Components.WoSwitch;
  }

  interface StencilIntrinsicElements {
    'wo-action-sheet': Components.WoActionSheetAttributes;
    'wo-button': Components.WoButtonAttributes;
    'wo-cell-group': Components.WoCellGroupAttributes;
    'wo-cell': Components.WoCellAttributes;
    'wo-color-choose': Components.WoColorChooseAttributes;
    'wo-count': Components.WoCountAttributes;
    'wo-main': Components.WoMainAttributes;
    'wo-mode': Components.WoModeAttributes;
    'wo-progress': Components.WoProgressAttributes;
    'wo-switch': Components.WoSwitchAttributes;
  }


  interface HTMLWoActionSheetElement extends Components.WoActionSheet, HTMLStencilElement {}
  var HTMLWoActionSheetElement: {
    prototype: HTMLWoActionSheetElement;
    new (): HTMLWoActionSheetElement;
  };

  interface HTMLWoButtonElement extends Components.WoButton, HTMLStencilElement {}
  var HTMLWoButtonElement: {
    prototype: HTMLWoButtonElement;
    new (): HTMLWoButtonElement;
  };

  interface HTMLWoCellGroupElement extends Components.WoCellGroup, HTMLStencilElement {}
  var HTMLWoCellGroupElement: {
    prototype: HTMLWoCellGroupElement;
    new (): HTMLWoCellGroupElement;
  };

  interface HTMLWoCellElement extends Components.WoCell, HTMLStencilElement {}
  var HTMLWoCellElement: {
    prototype: HTMLWoCellElement;
    new (): HTMLWoCellElement;
  };

  interface HTMLWoColorChooseElement extends Components.WoColorChoose, HTMLStencilElement {}
  var HTMLWoColorChooseElement: {
    prototype: HTMLWoColorChooseElement;
    new (): HTMLWoColorChooseElement;
  };

  interface HTMLWoCountElement extends Components.WoCount, HTMLStencilElement {}
  var HTMLWoCountElement: {
    prototype: HTMLWoCountElement;
    new (): HTMLWoCountElement;
  };

  interface HTMLWoMainElement extends Components.WoMain, HTMLStencilElement {}
  var HTMLWoMainElement: {
    prototype: HTMLWoMainElement;
    new (): HTMLWoMainElement;
  };

  interface HTMLWoModeElement extends Components.WoMode, HTMLStencilElement {}
  var HTMLWoModeElement: {
    prototype: HTMLWoModeElement;
    new (): HTMLWoModeElement;
  };

  interface HTMLWoProgressElement extends Components.WoProgress, HTMLStencilElement {}
  var HTMLWoProgressElement: {
    prototype: HTMLWoProgressElement;
    new (): HTMLWoProgressElement;
  };

  interface HTMLWoSwitchElement extends Components.WoSwitch, HTMLStencilElement {}
  var HTMLWoSwitchElement: {
    prototype: HTMLWoSwitchElement;
    new (): HTMLWoSwitchElement;
  };

  interface HTMLElementTagNameMap {
    'wo-action-sheet': HTMLWoActionSheetElement
    'wo-button': HTMLWoButtonElement
    'wo-cell-group': HTMLWoCellGroupElement
    'wo-cell': HTMLWoCellElement
    'wo-color-choose': HTMLWoColorChooseElement
    'wo-count': HTMLWoCountElement
    'wo-main': HTMLWoMainElement
    'wo-mode': HTMLWoModeElement
    'wo-progress': HTMLWoProgressElement
    'wo-switch': HTMLWoSwitchElement
  }

  interface ElementTagNameMap {
    'wo-action-sheet': HTMLWoActionSheetElement;
    'wo-button': HTMLWoButtonElement;
    'wo-cell-group': HTMLWoCellGroupElement;
    'wo-cell': HTMLWoCellElement;
    'wo-color-choose': HTMLWoColorChooseElement;
    'wo-count': HTMLWoCountElement;
    'wo-main': HTMLWoMainElement;
    'wo-mode': HTMLWoModeElement;
    'wo-progress': HTMLWoProgressElement;
    'wo-switch': HTMLWoSwitchElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
